### ISSUE TITLE
How can I get the targetFILE in SpliSER_diffSpliSER_analysis_forVersion014plus.Rmd

### ISSUE THREAD

**Issue by shangguandong1996** [CraigIDent/SpliSER#2]
Hi, Dr Dent.

I am reading your Rmd, but I find it seems that there is no information about producing `targetFILE` in 
https://github.com/CraigIDent/SpliSER/blob/7a29383362fea6a640e3473dd352e05481561a23/SpliSER_diffSpliSER_analysis_forVersion014plus.Rmd#L33

So I am wondering whether you can help me:)

Best wishes

Guandong Shang

**Comment by CraigIDent** [comment]
Hi, thanks for getting in touch.
I've updated the README file to explain how to create a target file (at the bottom of the README). I've also included an example target file that you can use as a starting point for your own data!
