### ISSUE TITLE
Duplicates Site

### ISSUE THREAD

**Issue by algaebrown** [CraigIDent/SpliSER#4]
Hi @CraigIDent, Thanks for making such a wonderful tool.

I ran it on some stranded RNA-seq data and found duplicated acceptor SSE values:
![image](https://github.com/CraigIDent/SpliSER/assets/17774672/93749371-cf2b-4f07-946b-78ad77a8ce43)

Please advise why there would be duplicated values for a single position on the same gene?
Thanks

I ran `SpliSER_v0_1_8.py`. Thanks

**Comment by CraigIDent** [comment]
Hi @algaebrown! Sorry I missed this one. 
Short answer is - it shouldn't be doing that. 
I guess you might have moved on from this analysis, but if you could send me an extract of the BAM and BED file that you were using for this region, it would help me figure out what has gone wrong. 
It looks like SpliSER has taken one (very rare) junction and not recognised that it uses the same 5' site as the junctions above. I haven't seen this issue before.
Best,
Craig

**Comment by CraigIDent** [comment]
This will sometimes (very rarely) happen with Illumina reads. If it is only 1 in every 42000 reads, like the example above, then I would suggest filtering the duplicated sites from the SpliSER results on the basis of alpha counts. 
If it were occurring more like 50% of the time, then it could be that the reads are not stranded to begin with - but that doesn't seem to be happening here.
